### ISSUE TITLE
Please add "Lochsa" as an option to the Watershed name drop-down

### ISSUE THREAD

**Issue by aagervasi** [SouthForkResearch/conductivity#12]
As part of the Riverscapes project functionality for both Pre-process Envir Param and Predict Conductivity

**Comment by jesselangdon** [comment]
All remaining watersheds should be added to Create Riverscapes Project tool dropdown list.

**Comment by jesselangdon** [comment]
Added all CHaMP/ISEMP watersheds (hopefully)
