### ISSUE TITLE
Predict Conductivity created output but fails to run in Riverscapes project

### ISSUE THREAD

**Issue by aagervasi** [SouthForkResearch/conductivity#13]
Error likely due to an issue with Realization naming convention. First I tried running with the Realization "Conductivity Run 01" which is what I usually name the Realizations at the Pre-process Environmental Parameters step. This failed so I opened up the xml and it looked like it set the name of the Realization to 'Run01' which I then tried running as the Realization name, which resulted in another error and the message below:
![predconductivityfailure](https://user-images.githubusercontent.com/25061462/29432452-88ea26cc-8350-11e7-8798-e8c68128817c.png)

Data:
https://www.dropbox.com/home/Riverscapes_share?preview=LowerSelway_Conductivity.zip

**Comment by jesselangdon** [comment]
Here's what I assume is an error message that was similar to Arielle's first error:

![image](https://user-images.githubusercontent.com/2524993/29602211-10380d82-8794-11e7-9fb4-d1d0699f70ff.png)

I need to add a more graceful error message if there is a problem with writing to an exisiting project.rs.xml file...

**Comment by jesselangdon** [comment]
I ended up refactoring the Conductivity Tools into an ESRI Python Toolbox, from a .tbx to a .pyt file.  Also added a Create Riverscapes Project tool to the toolbox.

See commit https://github.com/Riverscapes/Conductivity/commit/ce0ac7d7520f1f9aa73ff4932279e7247c3eb244
