### ISSUE TITLE
Error Executing Riverscapes CreateProjectTool

### ISSUE THREAD

**Issue by aagervasi** [SouthForkResearch/conductivity#15]
Hopefully that's legible
![unfclearwater_conductivityriverscapeserror](https://user-images.githubusercontent.com/25061462/29690919-df2ababe-88dd-11e7-9c36-ab741e5beae5.png)

**Comment by aagervasi** [comment]
Pretty straightforward inputs:
![screenshot 2017-08-25 08 50 18](https://user-images.githubusercontent.com/25061462/29721569-92459ad0-8972-11e7-8f66-bb6272aa722e.png)

**Comment by jesselangdon** [comment]
Fixed the line causing this issue.

See commit: https://github.com/Riverscapes/Conductivity/commit/591602a3cf8077b4e21f632a68f58a1368e173c7

**Comment by aagervasi** [comment]
Conductivity Tools v. 1.0.3 

It appears as if the same issue is occurring somewhere in the Pre-process Environmental Parameters Tool. As you can see on the right, the folders were set-up correctly in the Riverscapes repository using the first Conductivity tool, and the cond_param.dbf was successfully generated into the Model folder, but the files were not written into the xml for what appears to be the same "2 arguments" reason (sorry, maybe I'll be able to understand this a little bit better and fix it once I get into my Python book!)
I'll attach data and xml as well if needed.

![screenshot 2017-08-30 13 23 00](https://user-images.githubusercontent.com/25061462/29893506-27054162-8d87-11e7-944f-39332eaf82de.png)

**Comment by jesselangdon** [comment]
Forgot to change the called function here...

See commit https://github.com/Riverscapes/Conductivity/commit/b3af3801ef4206faa60e61a7037f601a8a5a2d4a
