### ISSUE TITLE
Riverscapes workspace folders not recognized in Pre-process Envir Parameters

### ISSUE THREAD

**Issue by aagervasi** [SouthForkResearch/conductivity#16]
Using Conductivity dev v1.0.2 on 8/28/2017 (pyt version). 
Ran Create Riverscapes project in the Riverscapes folder.
Tried to execute Pre-Process Environmental Parameters but the tool does not recognize the file formatting inside the Workspace (Riverscapes folder)

**Comment by aagervasi** [comment]
![screenshot 2017-08-28 14 12 42](https://user-images.githubusercontent.com/25061462/29797232-c8639fdc-8c0a-11e7-9936-ed59712f30a9.png)
![screenshot 2017-08-28 14 12 48](https://user-images.githubusercontent.com/25061462/29797239-cb6fbf62-8c0a-11e7-9d37-e4ac2d6085a6.png)

**Comment by aagervasi** [comment]
Data:
https://www.dropbox.com/home/Riverscapes_share?preview=UNFClearwater.zip

**Comment by jesselangdon** [comment]
Fixed a problem that I actually introduced a couple of commits back.

See commit:
https://github.com/Riverscapes/Conductivity/commit/7308448cf8c28b2c9c9503b8179900791e86d8b6
